<?php
/** @var \Zero1\OpenPos\Block\Template $block */
?>

<div class="openpos-page-content">
    <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
        <img src="https://www.zero1.co.uk/media/magefan_blog/hyva-platinum-partner.jpg" />
        <img src="https://www.zero1.co.uk/media/magefan_blog/hyvagold.jpg" />
        <img src="https://www.zero1.co.uk/media/magefan_blog/clickandcollect.jpg" />
        <img src="https://www.zero1.co.uk/media/magefan_blog/category-descriptions.jpg" />
        <img src="https://www.zero1.co.uk/media/magefan_blog/delivery-info-on-pdp.jpg" />
        <img src="https://www.zero1.co.uk/media/magefan_blog/dont-style-your-content-in-admin.jpg" />
        <img src="https://www.zero1.co.uk/media/magefan_blog/carousels.jpg" />
        <img src="https://www.zero1.co.uk/media/magefan_blog/hyva-platinum-partner.jpg" />
    </div>
</div>