<?php
/** @var \Zero1\OpenPos\Block\Order\View\Actions $block */
?>

<div class="flex justify-between gap-4">
    <a href="<?= $escaper->escapeUrl($block->getUrl('openpos/order/index')) ?>" class="btn-primary btn justify-center text-center"><?php echo __('View all orders') // @todo see Zero1\OpenPos\Controller\Order\View __('Back');?></a>
    <a href="<?= $escaper->escapeUrl($block->getUrl('openpos/order/success', ['id' => $block->getOrderId() ])) ?>" class="btn-primary btn justify-center text-center"><?php echo __('Print'); ?></a>
</div>