<div id="zero-1-hyva-pos-auto-add" class="relative w-full flex px-6 flex-col <?= !$magewire->isVisible ? 'hidden' : '' ?>">
    <?php if ($magewire->isVisible): ?>
        <style>.switcher-button-openposautoadd {display: none;}</style>

        <?php if ($magewire->customProductMode): ?>
            <div class="relative w-full flex flex-col">
                <div class="w-full mb-4">
                    <span class="font-bold inline-block mb-4 w-full"><?php echo __('Add A Custom Product'); ?></span>
                    <input id="description-input" placeholder="Name / description..." wire:model.defer="descriptionInput" class="bg-c-highlight w-full text-lg leading-normal transition appearance-none text-grey-800 outline-none border form-input" />
                    <input id="custom-price-input" wire:model.defer="customPriceInput" type="number" placeholder="Price..." class="mt-4 bg-c-highlight w-full text-lg leading-normal transition appearance-none text-grey-800 outline-none border form-input" />
                    <button class="btn mt-4 c-secondary-cta" wire:click="parseSkuInput"><?php echo __('Add'); ?></button>
                </div>
                <div class="w-full flex">
                    <span class="cancel underline p-6 w-full text-center text-sm" wire:click="resetInput"><?php echo __('Cancel'); ?></span>
                </div>
            </div>
            <style>#openpos-switcher {display: none;}</style>
        <?php endif; ?>

        <?php if ($magewire->priceEditorMode): ?>
            <div class="relative w-full flex flex-col">
                <div class="w-full mb-4">
                    <span class="font-bold inline-block mb-2 w-full"><?php echo __('Custom Pricing'); ?></span>
                    <span class="inline-block text-grey-800"><?php echo __('Enter a custom price below of the product you are about to scan'); ?></span>
                    <input id="custom-price-input" wire:model.defer="customPriceInput" type="number" placeholder="Price..." class="mt-4 bg-c-highlight w-full text-lg leading-normal transition appearance-none text-grey-800 outline-none border form-input" />
                    <input id="z1-auto-add"
                        autocomplete="off"
                        name="z1-auto-add"
                        wire:keydown.<?= $magewire->getExitCharacter() ?>="parseSkuInput"
                        placeholder="<?= $escaper->escapeHtmlAttr(__('Scan product or enter SKU...')) ?>"
                        class="mt-6 w-full text-lg leading-normal transition appearance-none text-grey-800 outline-none border form-input bg-c-highlight"
                        wire:model.defer="skuInput" />
                </div>
                <div class="w-full flex">
                    <span class="cancel underline p-6 w-full text-center text-sm" wire:click="resetInput"><?php echo __('Cancel'); ?></span>
                </div>
            </div>
            <style>#openpos-switcher {display: none;}</style>
        <?php endif; ?>

        <?php // Don't show regular search field if in other modes 
        ?>
        <?php if (!$magewire->customProductMode && !$magewire->priceEditorMode): ?>
            <?php if ($magewire->showSkuField): ?>
                <div class="relative w-full flex mb-4">
                    <input id="z1-auto-add"
                        autocomplete="off"
                        name="z1-auto-add"
                        wire:keydown.<?= $magewire->getExitCharacter() ?>="parseSkuInput"
                        placeholder="<?= $escaper->escapeHtmlAttr(__('Start scanning or search for products...')) ?>"
                        class="w-full text-lg leading-normal transition appearance-none text-grey-800 outline-none border form-input bg-c-highlight"
                        wire:model.defer="skuInput" />
                    <script>
                        document.getElementById("z1-auto-add").focus();
                    </script>

                </div>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
</div>