<div id="zero-1-hyva-pos-auto-add" class="px-6">
    <div class="relative w-full flex">
        <?php if($magewire->superMode): ?>
          custom price:
          <input id="custom-price-input" wire:model.defer="customPriceInput" />
        <?php endif; ?>
        <input id="z1-auto-add"
            autocomplete="off"
            name="z1-auto-add"
            wire:blur="addProduct" 
            placeholder="<?= $escaper->escapeHtmlAttr(__('Scan Barcode or enter SKU / search term')) ?>"
            class="w-full p-2 text-sm leading-normal transition appearance-none text-grey-800
            outline-none lg:text-lg border px-4"
            wire:model.defer="skuInput"
        />
        <button class="btn">Search</button>
    </div>

<script>

  const autoadd = document.querySelector('input[id="z1-auto-add"]');
  autoadd.addEventListener("blur", (event) => {
    document.getElementById("z1-auto-add").clear();
    document.getElementById("z1-auto-add").focus();
  });
  document.getElementById("z1-auto-add").focus();

</script>
</div>
